<?php

namespace Titan\Tests\Feature;

use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Titan\Area;
use Titan\Character;
use Titan\Tests\TestCase;
use Titan\User;

class LoginTest extends TestCase
{
    use RefreshDatabase;

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testLoginLoadsWhenNotLoggedIn()
    {
        $response = $this->get('/login');

        $response->assertStatus(200);
    }

    public function testLoginRedirectsToCharacterChoiceWhenLoggedIn()
    {
        $user = factory(User::class)->make();

        $res = $this->actingAs($user)
            ->get('login')
            ->assertSeeText("You must choose your character first");
    }

    public function testLoginRedirectsToGameWhenLoggedInAndHasCharacter()
    {
        $user = factory(User::class)->create();

        $character = new Character();
        $character->user_id = $user->id;
        $character->display_name = 'Demo';
        $character->save();

        $character->seedStats();

        $user->last_character_played = $character->id;
        $user->save();

        $res = $this->actingAs($user)
            ->withSession([
                'character_logged_in' => $character->id
            ])
            ->get('login')
            ->assertSeeText("Game home page");

    }

    public function testLoginWorks()
    {
        $user = factory(User::class)->create([
            'email' => 'demo@demo.com',
            'password' => Hash::make('password')
        ]);

        $res = $this->post('login', [
            'email' => 'demo@demo.com',
            'password' => 'password'
        ]);

        $this->assertAuthenticatedAs($user);
    }


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
