[package]
name = "titan-render-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
titan = { path = "../.." }
wgpu = { version = "30", features = ["webgl"] }
bytemuck = { version = "1", features = ["derive"] }

[dev-dependencies]
pollster = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
titan-protocol = { path = "../titan-protocol" }
