//! Transport-neutral inspection of a Titan [`App`](crate::App).

mod aliases;
mod browser;
mod capture;
#[cfg(all(target_arch = "wasm32", feature = "browser-capture"))]
pub use browser::response_promise;
pub use browser::{
    BrowserSession, dispatch_json_with_policy, dispatch_with_policy, handle_json_with_policy,
    handle_with_policy,
};
pub use capture::{CaptureCompleter, CaptureLimits, Dispatch, PendingCapture};
#[cfg(all(target_arch = "wasm32", feature = "browser-capture"))]
pub use js_sys::Promise as BrowserPromise;
use std::sync::{
    Arc,
    atomic::{AtomicU64, AtomicUsize, Ordering},
};
use titan_protocol::CaptureIdentity;

use std::collections::BTreeMap;
use std::time::Duration;
#[cfg(not(target_arch = "wasm32"))]
use std::time::Instant;

use serde::de::DeserializeOwned;
use titan_protocol::{
    Capabilities, CaptureResult, CommandMetadata, EntityDetails, EntityId, EntityPage,
    EntitySummary, ErrorCode, InputValue, Operation, QueryMetadata, Request, RequestEnvelope,
    Response, ResponseEnvelope, RunMode, RuntimeStatus, SCHEMA_VERSION,
};

use crate::{App, Component, Entity, FixedTime, Name, World};

pub use titan_protocol::{FieldMetadata, ProtocolError};

/// Opt-in component field registration, usually generated by [`crate::Inspect`].
/// Registration preserves the inspector's validation and mutation policy.
pub trait Inspect: Component {
    fn register_inspection(inspector: &mut Inspector) -> Result<(), ProtocolError>;
}

/// Runtime settings visible through inspection capabilities.
#[derive(Clone, Debug)]
pub struct InspectionConfig {
    pub instance_id: String,
    pub project: String,
    pub run_mode: RunMode,
    pub controlled: bool,
    pub mutation_enabled: bool,
}

impl InspectionConfig {
    pub fn controlled(instance_id: impl Into<String>, project: impl Into<String>) -> Self {
        Self {
            instance_id: instance_id.into(),
            project: project.into(),
            run_mode: RunMode::Headless,
            controlled: true,
            mutation_enabled: false,
        }
    }
}

/// Per-request limits for controlled stepping.
///
/// Frame limits apply on all targets. The cooperative wall-clock limit is
/// enforced only on native targets; browser hosts must bound execution with
/// frame limits or their own host clock. A running system cannot be interrupted.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StepBudget {
    pub max_frames: u64,
    /// `None` disables the native wall-clock limit. Zero permits no execution.
    pub max_duration: Option<Duration>,
}

impl StepBudget {
    pub const DEFAULT: Self = Self {
        max_frames: 10_000,
        max_duration: Some(Duration::from_secs(5)),
    };
}

impl Default for StepBudget {
    fn default() -> Self {
        Self::DEFAULT
    }
}

// Preserve integer precision when comparing JSON integers against f64 metadata.
// Metadata bounds are finite; comparing via as_f64 alone rounds integers >2^53.
fn numeric_cmp(value: &serde_json::Value, bound: f64) -> std::cmp::Ordering {
    use std::cmp::Ordering;
    let integer_order = if let Some(integer) = value.as_i64() {
        if bound < i64::MIN as f64 {
            return Ordering::Greater;
        }
        if bound >= 9_223_372_036_854_775_808.0 {
            return Ordering::Less;
        }
        integer.cmp(&(bound as i64))
    } else if let Some(integer) = value.as_u64() {
        if bound < 0.0 {
            return Ordering::Greater;
        }
        if bound >= 18_446_744_073_709_551_616.0 {
            return Ordering::Less;
        }
        integer.cmp(&(bound as u64))
    } else {
        return value
            .as_f64()
            .expect("validated numeric field")
            .partial_cmp(&bound)
            .expect("finite values");
    };
    integer_order.then_with(|| 0.0_f64.partial_cmp(&bound.fract()).expect("finite bound"))
}

fn missing_component() -> ProtocolError {
    ProtocolError::new(
        ErrorCode::NotFound,
        "entity does not contain the requested component",
    )
}

type CommandHandler =
    Box<dyn FnMut(&mut App, serde_json::Value) -> Result<(), ProtocolError> + Send>;
type QueryHandler =
    Box<dyn FnMut(&App, serde_json::Value) -> Result<serde_json::Value, ProtocolError> + Send>;
struct RegisteredQuery {
    metadata: QueryMetadata,
    handler: QueryHandler,
}

type InputHandler = Box<
    dyn FnMut(&mut App, u64, &BTreeMap<String, InputValue>) -> Result<(), ProtocolError> + Send,
>;
type CaptureHandler = Box<dyn FnMut(&App) -> Result<CaptureResult, ProtocolError> + Send>;
type AsyncCaptureHandler =
    Box<dyn FnMut(&App, CaptureIdentity, CaptureCompleter) -> Result<(), ProtocolError> + Send>;

type FieldGetter = Box<dyn Fn(&World, Entity) -> Result<serde_json::Value, ProtocolError> + Send>;
type FieldSetter =
    Box<dyn Fn(&mut World, Entity, &serde_json::Value) -> Result<(), ProtocolError> + Send>;
struct RegisteredField {
    metadata: FieldMetadata,
    getter: FieldGetter,
    setter: Option<FieldSetter>,
}

struct RegisteredCommand {
    metadata: CommandMetadata,
    handler: CommandHandler,
}

/// Executes typed inspection requests at a caller-controlled safe point.
///
/// A transport adapter should enqueue requests and call [`handle`](Self::handle)
/// only when it has exclusive access to the application. Transport threads
/// must never access the ECS world directly.
pub struct Inspector {
    config: InspectionConfig,
    state_revision: u64,
    step_budget: StepBudget,
    commands: BTreeMap<String, RegisteredCommand>,
    queries: BTreeMap<String, RegisteredQuery>,
    fields: BTreeMap<String, BTreeMap<String, RegisteredField>>,
    component_aliases: BTreeMap<String, String>,
    input_handler: Option<InputHandler>,
    capture_handler: Option<CaptureHandler>,
    async_capture_handler: Option<AsyncCaptureHandler>,
    capture_dimensions: (u32, u32),
    capture_limits: CaptureLimits,
    capture_generation: Arc<AtomicU64>,
    capture_outstanding: Arc<AtomicUsize>,
    next_capture_id: u64,
}

impl Drop for Inspector {
    fn drop(&mut self) {
        self.reset_capture_session();
    }
}

impl Inspector {
    pub fn new(config: InspectionConfig) -> Self {
        Self {
            config,
            state_revision: 0,
            step_budget: StepBudget::DEFAULT,
            commands: BTreeMap::new(),
            queries: BTreeMap::new(),
            fields: BTreeMap::new(),
            component_aliases: BTreeMap::new(),
            input_handler: None,
            capture_handler: None,
            async_capture_handler: None,
            capture_dimensions: (1, 1),
            capture_limits: CaptureLimits::default(),
            capture_generation: Arc::new(AtomicU64::new(0)),
            capture_outstanding: Arc::new(AtomicUsize::new(0)),
            next_capture_id: 0,
        }
    }

    /// Registers a component's opt-in generated fields.
    /// Like manual registration, an error can leave earlier fields registered.
    pub fn register_inspectable<T: Inspect>(&mut self) -> Result<&mut Self, ProtocolError> {
        T::register_inspection(self)?;
        Ok(self)
    }

    /// Exposes a component field using the component's full Rust type name.
    /// JSON decoding, numeric metadata bounds, and the immutable validator run
    /// before the infallible setter receives mutable component access. Validators
    /// should enforce game invariants; setters should assign only the field.
    /// Duplicate or blank field names and invalid numeric bounds are rejected.
    pub fn register_field<T: Component, V: serde::Serialize + DeserializeOwned + 'static>(
        &mut self,
        field: impl Into<String>,
        mut metadata: FieldMetadata,
        getter: impl Fn(&T) -> V + Send + 'static,
        validate: impl Fn(&T, &V) -> Result<(), ProtocolError> + Send + 'static,
        setter: impl Fn(&mut T, V) + Send + 'static,
    ) -> Result<&mut Self, ProtocolError> {
        metadata.writable = true;
        let bounds = metadata.clone();
        self.insert_field::<T>(
            field.into(),
            metadata,
            Box::new(move |world, entity| {
                let component = world.get::<T>(entity).ok_or_else(missing_component)?;
                serde_json::to_value(getter(component)).map_err(|error| {
                    ProtocolError::new(
                        ErrorCode::Internal,
                        format!("serializing component field: {error}"),
                    )
                })
            }),
            Some(Box::new(move |world, entity, value| {
                let component = world.get::<T>(entity).ok_or_else(missing_component)?;
                let decoded: V = serde_json::from_value(value.clone()).map_err(|error| {
                    ProtocolError::new(
                        ErrorCode::InvalidValue,
                        format!("invalid field value: {error}"),
                    )
                })?;
                if bounds.minimum.is_some() || bounds.maximum.is_some() {
                    value
                        .as_f64()
                        .filter(|value| value.is_finite())
                        .ok_or_else(|| {
                            ProtocolError::new(
                                ErrorCode::InvalidValue,
                                "bounded field requires a finite numeric value",
                            )
                        })?;
                    if bounds
                        .minimum
                        .is_some_and(|minimum| numeric_cmp(value, minimum).is_lt())
                        || bounds
                            .maximum
                            .is_some_and(|maximum| numeric_cmp(value, maximum).is_gt())
                    {
                        return Err(ProtocolError::new(
                            ErrorCode::InvalidValue,
                            "field value is outside its declared bounds",
                        ));
                    }
                }
                validate(component, &decoded)?;
                setter(
                    world.get_mut::<T>(entity).ok_or_else(missing_component)?,
                    decoded,
                );
                Ok(())
            })),
        )
    }

    /// Exposes a read-only field; registration does not enable runtime mutation.
    pub fn register_read_only_field<T: Component, V: serde::Serialize + 'static>(
        &mut self,
        field: impl Into<String>,
        mut metadata: FieldMetadata,
        getter: impl Fn(&T) -> V + Send + 'static,
    ) -> Result<&mut Self, ProtocolError> {
        metadata.writable = false;
        self.insert_field::<T>(
            field.into(),
            metadata,
            Box::new(move |world, entity| {
                let component = world.get::<T>(entity).ok_or_else(missing_component)?;
                serde_json::to_value(getter(component)).map_err(|error| {
                    ProtocolError::new(
                        ErrorCode::Internal,
                        format!("serializing component field: {error}"),
                    )
                })
            }),
            None,
        )
    }

    fn insert_field<T: Component>(
        &mut self,
        field: String,
        metadata: FieldMetadata,
        getter: FieldGetter,
        setter: Option<FieldSetter>,
    ) -> Result<&mut Self, ProtocolError> {
        let component = std::any::type_name::<T>();
        self.validate_component_identity(component)?;
        if field.trim().is_empty()
            || self
                .fields
                .get(component)
                .is_some_and(|fields| fields.contains_key(&field))
        {
            return Err(ProtocolError::new(
                ErrorCode::InvalidValue,
                "component field name must be nonempty and unique",
            ));
        }
        if metadata.minimum.is_some_and(|value| !value.is_finite())
            || metadata.maximum.is_some_and(|value| !value.is_finite())
            || metadata
                .minimum
                .zip(metadata.maximum)
                .is_some_and(|(min, max)| min > max)
        {
            return Err(ProtocolError::new(
                ErrorCode::InvalidValue,
                "field bounds must be finite and ordered",
            ));
        }
        self.fields.entry(component.into()).or_default().insert(
            field,
            RegisteredField {
                metadata,
                getter,
                setter,
            },
        );
        Ok(self)
    }

    /// Explicitly registered field descriptions, including components with no instances.
    pub fn component_field_metadata(&self) -> BTreeMap<String, BTreeMap<String, FieldMetadata>> {
        self.fields
            .iter()
            .map(|(component, fields)| {
                (
                    self.component_name(component).to_owned(),
                    fields
                        .iter()
                        .map(|(name, field)| (name.clone(), field.metadata.clone()))
                        .collect(),
                )
            })
            .collect()
    }

    /// Configures limits for subsequent controlled step requests.
    ///
    /// Oversized frame requests fail before startup or world mutation. Native
    /// timeouts are checked around startup and between complete ticks, so they
    /// may leave completed work visible without advancing the success revision.
    pub fn set_step_budget(&mut self, budget: StepBudget) -> &mut Self {
        self.step_budget = budget;
        self
    }

    /// Registers a game command with typed JSON-object arguments.
    ///
    /// Handlers run with exclusive application access. Validate before mutating:
    /// failed handlers and deferred operations are reported but are not rolled back.
    /// Use `#[serde(deny_unknown_fields)]` on argument types to reject extra fields.
    /// Duplicate or blank names are rejected without replacing an existing command.
    pub fn register_command<A: DeserializeOwned + 'static>(
        &mut self,
        metadata: CommandMetadata,
        mut handler: impl FnMut(&mut App, A) -> Result<(), ProtocolError> + Send + 'static,
    ) -> Result<&mut Self, ProtocolError> {
        if metadata.name.trim().is_empty() || self.commands.contains_key(&metadata.name) {
            return Err(ProtocolError::new(
                ErrorCode::InvalidValue,
                "command name must be nonempty and unique",
            ));
        }
        self.commands.insert(
            metadata.name.clone(),
            RegisteredCommand {
                metadata,
                handler: Box::new(move |app, value| {
                    let arguments = serde_json::from_value(value).map_err(|error| {
                        ProtocolError::new(
                            ErrorCode::InvalidValue,
                            format!("invalid command arguments: {error}"),
                        )
                    })?;
                    handler(app, arguments)
                }),
            },
        );
        Ok(self)
    }

    /// Registers a read-only query of game-owned state without exposing mutation.
    /// Queries receive shared application access, do not drain deferred writes,
    /// and do not increment the revision. Keep returned data bounded.
    pub fn register_query<A: DeserializeOwned + 'static>(
        &mut self,
        metadata: QueryMetadata,
        mut handler: impl FnMut(&App, A) -> Result<serde_json::Value, ProtocolError> + Send + 'static,
    ) -> Result<&mut Self, ProtocolError> {
        if metadata.name.trim().is_empty() || self.queries.contains_key(&metadata.name) {
            return Err(ProtocolError::new(
                ErrorCode::InvalidValue,
                "query name must be nonempty and unique",
            ));
        }
        self.queries.insert(
            metadata.name.clone(),
            RegisteredQuery {
                metadata,
                handler: Box::new(move |app, value| {
                    let arguments = serde_json::from_value(value).map_err(|error| {
                        ProtocolError::new(
                            ErrorCode::InvalidValue,
                            format!("invalid query arguments: {error}"),
                        )
                    })?;
                    handler(app, arguments)
                }),
            },
        );
        Ok(self)
    }

    /// Reflect whether the host has paused its clock for inspector stepping.
    /// The host owns the safe-point transition and its revision accounting.
    pub fn set_controlled(&mut self, controlled: bool) {
        self.config.controlled = controlled;
    }
    pub fn is_controlled(&self) -> bool {
        self.config.controlled
    }
    pub fn set_run_mode(&mut self, run_mode: RunMode) {
        self.config.run_mode = run_mode;
    }
    pub fn set_mutation_enabled(&mut self, enabled: bool) {
        self.config.mutation_enabled = enabled;
    }

    /// Account for local host changes, such as restart, outside request handling.
    /// Call at the same exclusive safe point as the change. Observed frame remains
    /// the simulation clock; revision also distinguishes changes at that frame.
    pub fn note_external_change(&mut self) {
        self.state_revision = self.state_revision.wrapping_add(1);
    }

    /// Installs the game's deterministic input adapter, replacing any prior hook.
    /// The adapter validates actions and queues them for the requested future frame.
    /// Deferred writes are applied before and after the hook, including on failure.
    /// Like commands, hooks are not transactional; validate before mutating.
    pub fn register_input_handler(
        &mut self,
        handler: impl FnMut(&mut App, u64, &BTreeMap<String, InputValue>) -> Result<(), ProtocolError>
        + Send
        + 'static,
    ) -> &mut Self {
        self.input_handler = Some(Box::new(handler));
        self
    }

    /// Installs a read-only capture adapter, replacing any prior hook.
    pub fn register_capture_handler(
        &mut self,
        handler: impl FnMut(&App) -> Result<CaptureResult, ProtocolError> + Send + 'static,
    ) -> &mut Self {
        self.async_capture_handler = None;
        self.capture_handler = Some(Box::new(handler));
        self
    }

    pub fn capture_timeout(&self) -> Duration {
        self.capture_limits.timeout
    }

    /// Set bounds before registering/dispatching capture work.
    pub fn set_capture_limits(&mut self, limits: CaptureLimits) -> &mut Self {
        self.capture_limits = limits;
        self
    }
    /// Declare output size; resizing affects only future captures.
    pub fn set_capture_dimensions(&mut self, width: u32, height: u32) -> &mut Self {
        self.capture_dimensions = (width, height);
        self
    }
    /// Invalidate old work when replacing/resetting the runtime, even at the same tick.
    pub fn reset_capture_session(&mut self) {
        self.capture_generation.fetch_add(1, Ordering::AcqRel);
    }
    /// Freeze owned immutable frame/assets here, at the application safe point.
    /// Keep the completer alive until asynchronous resources have been reclaimed.
    pub fn register_async_capture_handler(
        &mut self,
        width: u32,
        height: u32,
        handler: impl FnMut(&App, CaptureIdentity, CaptureCompleter) -> Result<(), ProtocolError>
        + Send
        + 'static,
    ) -> &mut Self {
        self.capture_dimensions = (width, height);
        self.capture_handler = None;
        self.async_capture_handler = Some(Box::new(handler));
        self
    }
    fn capture_identity(&mut self, app: &App, width: u32, height: u32) -> CaptureIdentity {
        self.next_capture_id = self
            .next_capture_id
            .checked_add(1)
            .expect("capture ID exhausted");
        CaptureIdentity {
            instance_id: self.config.instance_id.clone(),
            session_generation: self.capture_generation.load(Ordering::Acquire),
            capture_id: self.next_capture_id,
            observed_frame: current_frame(app),
            state_revision: self.state_revision,
            width,
            height,
        }
    }
    /// Dispatch at a safe point; pending work owns no application reference.
    pub fn dispatch(&mut self, app: &mut App, request: &RequestEnvelope) -> Dispatch {
        if !matches!(request.request, Request::Capture)
            || request.request_id.len() > 256
            || self.config.instance_id.len() > 256
            || self.async_capture_handler.is_none()
            || request.schema_version != SCHEMA_VERSION
            || request
                .target_instance
                .as_ref()
                .is_some_and(|target| target != &self.config.instance_id)
        {
            return Dispatch::Ready(self.handle(app, request));
        }
        let (width, height) = self.capture_dimensions;
        if let Err(error) = self.capture_limits.validate_dimensions(width, height) {
            return Dispatch::Ready(self.failure(app, request, error));
        }
        if self.capture_outstanding.load(Ordering::Acquire) >= self.capture_limits.max_outstanding {
            let mut error = ProtocolError::new(
                ErrorCode::Busy,
                "capture capacity is occupied; wait for resource reclamation",
            );
            error.retryable = true;
            return Dispatch::Ready(self.failure(app, request, error));
        }
        let identity = self.capture_identity(app, width, height);
        let (pending, completer) = PendingCapture::new(
            request.clone(),
            identity.clone(),
            self.capture_generation.clone(),
            self.capture_outstanding.clone(),
            self.capture_limits,
        );
        if let Err(error) = self.async_capture_handler.as_mut().unwrap()(app, identity, completer) {
            return Dispatch::Ready(self.failure(app, request, error));
        }
        Dispatch::Pending(pending)
    }

    /// Returns registered command descriptions in deterministic name order.
    pub fn command_metadata(&self) -> Vec<CommandMetadata> {
        self.commands
            .values()
            .map(|command| command.metadata.clone())
            .collect()
    }

    pub fn handle(&mut self, app: &mut App, request: &RequestEnvelope) -> ResponseEnvelope {
        if matches!(request.request, Request::Capture)
            && (request.request_id.len() > 256 || self.config.instance_id.len() > 256)
        {
            let mut bounded = request.clone();
            bounded.request_id = request.request_id.chars().take(64).collect();
            return ResponseEnvelope::failure(
                &bounded,
                self.config.instance_id.chars().take(64).collect::<String>(),
                current_frame(app),
                self.state_revision,
                ProtocolError::new(
                    ErrorCode::InvalidValue,
                    "capture request and instance IDs must be at most 256 bytes; invalid IDs are truncated in this rejection",
                ),
            );
        }
        if request.schema_version != SCHEMA_VERSION {
            return self.failure(
                app,
                request,
                ProtocolError::new(
                    ErrorCode::ProtocolMismatch,
                    format!(
                        "runtime schema is {SCHEMA_VERSION}, request schema is {}",
                        request.schema_version
                    ),
                ),
            );
        }
        if request
            .target_instance
            .as_ref()
            .is_some_and(|target| target != &self.config.instance_id)
        {
            return self.failure(
                app,
                request,
                ProtocolError::new(
                    ErrorCode::NotFound,
                    "target runtime instance does not match",
                ),
            );
        }

        let result = self.execute(app, &request.request);
        match result {
            Ok(response) => ResponseEnvelope::success(
                request,
                &self.config.instance_id,
                current_frame(app),
                self.state_revision,
                response,
            ),
            Err(error) => self.failure(app, request, error),
        }
    }

    fn advance_with_budget(&self, app: &mut App, frames: u64) -> Result<(), ProtocolError> {
        if frames > self.step_budget.max_frames {
            let mut error =
                ProtocolError::new(ErrorCode::InvalidValue, "step frame budget exceeded");
            error
                .details
                .insert("requested_frames".into(), frames.into());
            error
                .details
                .insert("max_frames".into(), self.step_budget.max_frames.into());
            return Err(error);
        }
        #[cfg(not(target_arch = "wasm32"))]
        let started = Instant::now();
        #[cfg(not(target_arch = "wasm32"))]
        self.check_step_time(started, frames, 0)?;
        // Preserve checked stepping's startup and outstanding-error handling,
        // including for a zero-frame request.
        app.try_advance_fixed(0).map_err(deferred_failure)?;
        for completed in 0..frames {
            #[cfg(not(target_arch = "wasm32"))]
            self.check_step_time(started, frames, completed)?;
            #[cfg(target_arch = "wasm32")]
            let _ = completed;
            app.try_advance_fixed(1).map_err(deferred_failure)?;
        }
        #[cfg(not(target_arch = "wasm32"))]
        self.check_step_time(started, frames, frames)?;
        Ok(())
    }

    #[cfg(not(target_arch = "wasm32"))]
    fn check_step_time(
        &self,
        started: Instant,
        requested_frames: u64,
        completed_frames: u64,
    ) -> Result<(), ProtocolError> {
        let Some(limit) = self.step_budget.max_duration else {
            return Ok(());
        };
        let elapsed = started.elapsed();
        if elapsed < limit {
            return Ok(());
        }
        let mut error = ProtocolError::new(ErrorCode::Timeout, "step wall-clock budget exceeded");
        error
            .details
            .insert("requested_frames".into(), requested_frames.into());
        error
            .details
            .insert("completed_frames".into(), completed_frames.into());
        error.details.insert(
            "max_duration_us".into(),
            u64::try_from(limit.as_micros()).unwrap_or(u64::MAX).into(),
        );
        error.details.insert(
            "elapsed_us".into(),
            u64::try_from(elapsed.as_micros())
                .unwrap_or(u64::MAX)
                .into(),
        );
        Err(error)
    }

    fn execute(&mut self, app: &mut App, request: &Request) -> Result<Response, ProtocolError> {
        if matches!(request, Request::Entities { .. } | Request::Entity { .. }) {
            self.validate_component_aliases(app.world())?;
        }
        match request {
            Request::Capabilities => Ok(Response::Capabilities(self.capabilities())),
            Request::Status => Ok(Response::Status(RuntimeStatus {
                project: self.config.project.clone(),
                run_mode: self.config.run_mode,
                current_frame: current_frame(app),
                paused: self.config.controlled,
            })),
            Request::Entities { query, page } => {
                if page.limit == 0 {
                    return Err(ProtocolError::new(
                        ErrorCode::InvalidValue,
                        "entity page limit must be positive",
                    ));
                }
                let start = match page.cursor.as_deref() {
                    Some(cursor) => cursor.parse::<usize>().map_err(|_| {
                        ProtocolError::new(ErrorCode::InvalidValue, "invalid entity page cursor")
                    })?,
                    None => 0,
                };
                let limit = usize::try_from(page.limit.min(1_000)).unwrap_or(1_000);
                let matches: Vec<_> = app
                    .world()
                    .entities()
                    .filter_map(|entity| {
                        let name = app.world().get::<Name>(entity).map(|name| name.to_string());
                        let mut components: Vec<_> = app
                            .world()
                            .component_type_names(entity)
                            .into_iter()
                            .map(|name| self.component_name(name).to_owned())
                            .collect();
                        components.sort();
                        let name_matches = query
                            .name
                            .as_ref()
                            .is_none_or(|query_name| name.as_ref() == Some(query_name));
                        let components_match = query
                            .with_components
                            .iter()
                            .all(|required| components.contains(required));
                        (name_matches && components_match).then_some(EntitySummary {
                            id: to_protocol_entity(entity),
                            name,
                            components,
                        })
                    })
                    .collect();
                let entities = matches.iter().skip(start).take(limit).cloned().collect();
                let consumed = start.saturating_add(limit).min(matches.len());
                let next_cursor = (consumed < matches.len()).then(|| consumed.to_string());
                Ok(Response::Entities(EntityPage {
                    entities,
                    next_cursor,
                }))
            }
            Request::Entity { entity } => {
                let entity = crate::Entity::from_parts(entity.index, entity.generation);
                if !app.world().is_alive(entity) {
                    return Err(ProtocolError::new(
                        ErrorCode::NotFound,
                        "entity is not alive",
                    ));
                }
                let components = app
                    .world()
                    .component_type_names(entity)
                    .into_iter()
                    .map(|name| {
                        let value = match self.fields.get(name) {
                            Some(fields) => serde_json::Value::Object(
                                fields
                                    .iter()
                                    .map(|(name, field)| {
                                        Ok((name.clone(), (field.getter)(app.world(), entity)?))
                                    })
                                    .collect::<Result<_, ProtocolError>>()?,
                            ),
                            None => serde_json::Value::Null,
                        };
                        Ok((self.component_name(name).to_owned(), value))
                    })
                    .collect::<Result<BTreeMap<_, _>, ProtocolError>>()?;
                Ok(Response::Entity(EntityDetails {
                    id: to_protocol_entity(entity),
                    name: app.world().get::<Name>(entity).map(|name| name.to_string()),
                    component_fields: self
                        .component_field_metadata()
                        .into_iter()
                        .filter(|(name, _)| components.contains_key(name))
                        .collect(),
                    components,
                }))
            }
            Request::Step { frames } => {
                if !self.config.controlled {
                    return Err(ProtocolError::new(
                        ErrorCode::NotControlled,
                        "the runtime clock is not controlled by the inspector",
                    ));
                }
                self.advance_with_budget(app, *frames)?;
                self.state_revision = self.state_revision.wrapping_add(1);
                Ok(Response::Stepped {
                    frames: *frames,
                    current_frame: current_frame(app),
                })
            }
            Request::SetField { .. } if !self.config.mutation_enabled => Err(ProtocolError::new(
                ErrorCode::MutationDisabled,
                "runtime mutation was not explicitly enabled",
            )),
            Request::SetField {
                entity,
                component,
                field,
                value,
            } => {
                let entity = Entity::from_parts(entity.index, entity.generation);
                if !app.world().is_alive(entity) {
                    return Err(ProtocolError::new(
                        ErrorCode::NotFound,
                        "entity is not alive",
                    ));
                }
                self.validate_component_aliases(app.world())?;
                let component = self
                    .component_identity(component)
                    .ok_or_else(missing_component)?;
                if !app
                    .world()
                    .component_type_names(entity)
                    .contains(&component)
                {
                    return Err(missing_component());
                }
                let registered = self
                    .fields
                    .get(component)
                    .and_then(|fields| fields.get(field))
                    .ok_or_else(|| {
                        ProtocolError::new(
                            ErrorCode::ReadOnly,
                            "component field is not registered for mutation",
                        )
                    })?;
                let setter = registered.setter.as_ref().ok_or_else(|| {
                    ProtocolError::new(ErrorCode::ReadOnly, "component field is read-only")
                })?;
                setter(app.world_mut(), entity, value)?;
                self.state_revision = self.state_revision.wrapping_add(1);
                Ok(Response::Applied {
                    applied_frame: current_frame(app),
                })
            }
            Request::Queries => Ok(Response::Queries {
                queries: self
                    .queries
                    .values()
                    .map(|query| query.metadata.clone())
                    .collect(),
            }),
            Request::Query { name, arguments } => {
                let query = self.queries.get_mut(name).ok_or_else(|| {
                    ProtocolError::new(ErrorCode::NotFound, "query is not registered")
                })?;
                let value = (query.handler)(
                    app,
                    serde_json::Value::Object(arguments.clone().into_iter().collect()),
                )?;
                Ok(Response::QueryResult { value })
            }
            Request::Commands => Ok(Response::Commands {
                commands: self
                    .commands
                    .values()
                    .map(|command| command.metadata.clone())
                    .collect(),
            }),
            Request::Invoke { name, arguments } => {
                let command = self.commands.get_mut(name).ok_or_else(|| {
                    ProtocolError::new(ErrorCode::NotFound, format!("unknown game command: {name}"))
                })?;
                app.apply_deferred().map_err(deferred_failure)?;
                let outcome = (command.handler)(
                    app,
                    serde_json::Value::Object(arguments.clone().into_iter().collect()),
                );
                // Always drain this invocation's deferred writes, even when the
                // handler rejects after enqueueing them. Commands are not transactional.
                let deferred = app.apply_deferred().map_err(deferred_failure);
                deferred?;
                outcome?;
                self.state_revision = self.state_revision.wrapping_add(1);
                Ok(Response::Applied {
                    applied_frame: current_frame(app),
                })
            }
            Request::InjectInput { frame, actions } => {
                let handler = self
                    .input_handler
                    .as_mut()
                    .ok_or_else(unregistered_operation)?;
                if !self.config.controlled {
                    return Err(ProtocolError::new(
                        ErrorCode::NotControlled,
                        "input injection requires a controlled runtime",
                    ));
                }
                if *frame <= current_frame(app) {
                    return Err(ProtocolError::new(
                        ErrorCode::InvalidValue,
                        "input must target a future frame",
                    ));
                }
                app.apply_deferred().map_err(deferred_failure)?;
                let outcome = handler(app, *frame, actions);
                app.apply_deferred().map_err(deferred_failure)?;
                outcome?;
                self.state_revision = self.state_revision.wrapping_add(1);
                Ok(Response::Applied {
                    applied_frame: *frame,
                })
            }
            Request::Capture => {
                let started = capture::CaptureTimer::new();
                let handler = self
                    .capture_handler
                    .as_mut()
                    .ok_or_else(unregistered_operation)?;
                let mut result = handler(app)?;
                self.capture_limits
                    .validate_dimensions(result.width, result.height)?;
                if result.artifact.len() > self.capture_limits.max_artifact_bytes
                    || result.format.len() > 64
                    || result.checksum.len() > 128
                {
                    return Err(ProtocolError::new(
                        ErrorCode::InvalidValue,
                        "capture artifact exceeds limit",
                    ));
                }
                result.identity = self.capture_identity(app, result.width, result.height);
                if serde_json::to_vec(&result).map_or(true, |bytes| bytes.len() > 3 * 1024 * 1024) {
                    return Err(ProtocolError::new(
                        ErrorCode::InvalidValue,
                        "capture response exceeds transport envelope limit",
                    ));
                }
                if started.elapsed() >= self.capture_limits.timeout {
                    return Err(ProtocolError::new(
                        ErrorCode::Timeout,
                        "capture deadline exceeded during response preparation",
                    ));
                }
                Ok(Response::Capture(result))
            }
        }
    }

    fn capabilities(&self) -> Capabilities {
        let mut operations = vec![Operation::Inspect];
        if self.config.controlled {
            operations.push(Operation::Step);
        }
        if self.config.mutation_enabled
            && self
                .fields
                .values()
                .any(|fields| fields.values().any(|field| field.setter.is_some()))
        {
            operations.push(Operation::Mutate);
        }
        if !self.commands.is_empty() {
            operations.push(Operation::Invoke);
        }
        if self.config.controlled && self.input_handler.is_some() {
            operations.push(Operation::InjectInput);
        }
        if !self.queries.is_empty() {
            operations.push(Operation::Query);
        }
        if self.capture_handler.is_some() || self.async_capture_handler.is_some() {
            operations.push(Operation::Capture);
        }
        Capabilities {
            schema_version: SCHEMA_VERSION,
            run_mode: self.config.run_mode,
            mutation_enabled: self.config.mutation_enabled,
            controlled: self.config.controlled,
            operations,
        }
    }

    fn failure(
        &self,
        app: &App,
        request: &RequestEnvelope,
        error: ProtocolError,
    ) -> ResponseEnvelope {
        ResponseEnvelope::failure(
            request,
            &self.config.instance_id,
            current_frame(app),
            self.state_revision,
            error,
        )
    }
}

fn unregistered_operation() -> ProtocolError {
    ProtocolError::new(
        ErrorCode::Unsupported,
        "this operation has not been registered by the game",
    )
}

fn deferred_failure(errors: Vec<crate::AppError>) -> ProtocolError {
    let mut error = ProtocolError::new(
        ErrorCode::Internal,
        "application schedule or deferred commands failed",
    );
    let mut deferred = Vec::new();
    let mut systems = Vec::new();
    for failure in errors {
        match failure {
            crate::AppError::Deferred(failure) => deferred.push(serde_json::json!({
                "entity": to_protocol_entity(failure.entity()),
                "operation": format!("{:?}", failure.operation()).to_lowercase(),
                "message": failure.to_string(),
            })),
            crate::AppError::System { system, error } => {
                let (kind, type_name) = match &error {
                    crate::SystemError::MissingResource { type_name } => {
                        ("missing_resource", *type_name)
                    }
                    crate::SystemError::ConflictingAccess { type_name, .. } => {
                        ("conflicting_access", *type_name)
                    }
                };
                systems.push(serde_json::json!({ "system": system, "kind": kind, "type_name": type_name, "message": error.to_string() }));
            }
        }
    }
    if !deferred.is_empty() {
        error
            .details
            .insert("deferred_errors".into(), deferred.into());
    }
    if !systems.is_empty() {
        error.details.insert("system_errors".into(), systems.into());
    }
    error
}

fn current_frame(app: &App) -> u64 {
    app.world()
        .resource::<FixedTime>()
        .expect("App always contains FixedTime")
        .tick()
}

fn to_protocol_entity(entity: crate::Entity) -> EntityId {
    EntityId {
        index: entity.index(),
        generation: entity.generation(),
    }
}

#[cfg(test)]
mod tests {
    use titan_protocol::{
        EntityId, EntityQuery, ErrorCode, PageRequest, Request, RequestEnvelope, Response,
        ResponseOutcome,
    };

    use super::{InspectionConfig, Inspector};
    use crate::{App, Component, FixedUpdate, Name};

    #[derive(Component)]
    struct Position(i32);

    fn inspected_app() -> (App, Inspector) {
        let mut app = App::new();
        let player = app.world_mut().spawn();
        app.world_mut().insert(player, Name::new("player")).unwrap();
        app.world_mut().insert(player, Position(0)).unwrap();
        app.add_systems(FixedUpdate, |world: &mut crate::World| {
            for (_, position) in world.iter_mut::<Position>() {
                position.0 += 1;
            }
        });
        let inspector = Inspector::new(InspectionConfig::controlled("instance-1", "test-game"));
        (app, inspector)
    }

    #[test]
    fn controlled_stepping_returns_the_exact_observed_frame() {
        let (mut app, mut inspector) = inspected_app();
        let request = RequestEnvelope::new("step", Request::Step { frames: 10 });

        let response = inspector.handle(&mut app, &request);

        assert_eq!(response.observed_frame, 10);
        assert_eq!(response.state_revision, 1);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Success {
                response: Response::Stepped {
                    frames: 10,
                    current_frame: 10
                }
            }
        ));
        assert_eq!(app.world().iter::<Position>().next().unwrap().1.0, 10);
    }

    #[test]
    fn oversized_steps_reject_before_startup_or_deferred_mutations() {
        let (mut app, mut inspector) = inspected_app();
        app.add_systems(crate::Startup, |_: &mut crate::World| panic!("startup ran"));
        let reserved = app.world_mut().commands().spawn();
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new("too-many", Request::Step { frames: 10_001 }),
        );
        assert_eq!(response.observed_frame, 0);
        assert_eq!(response.state_revision, 0);
        assert!(!app.world().is_alive(reserved));
        let ResponseOutcome::Failure { error } = response.outcome else {
            panic!("expected failure")
        };
        assert_eq!(error.code, ErrorCode::InvalidValue);
        assert_eq!(error.details["requested_frames"], 10_001);
        assert_eq!(error.details["max_frames"], 10_000);
    }

    #[test]
    fn configured_frame_budget_accepts_boundary_and_zero_steps() {
        let (mut app, mut inspector) = inspected_app();
        inspector.set_step_budget(super::StepBudget {
            max_frames: 2,
            max_duration: None,
        });
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new("boundary", Request::Step { frames: 2 }),
        );
        assert_eq!(response.observed_frame, 2);
        assert_eq!(response.state_revision, 1);
        assert!(matches!(response.outcome, ResponseOutcome::Success { .. }));
        let rejected = inspector.handle(
            &mut app,
            &RequestEnvelope::new("too-many", Request::Step { frames: 3 }),
        );
        assert_eq!(rejected.observed_frame, 2);
        assert_eq!(rejected.state_revision, 1);
        assert!(matches!(rejected.outcome, ResponseOutcome::Failure { .. }));
        let zero = inspector.handle(
            &mut app,
            &RequestEnvelope::new("zero", Request::Step { frames: 0 }),
        );
        assert_eq!(zero.observed_frame, 2);
        assert_eq!(zero.state_revision, 2);
        assert!(matches!(zero.outcome, ResponseOutcome::Success { .. }));
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn zero_wall_clock_budget_rejects_without_running_startup() {
        let (mut app, mut inspector) = inspected_app();
        app.add_systems(crate::Startup, |_: &mut crate::World| panic!("startup ran"));
        inspector.set_step_budget(super::StepBudget {
            max_frames: 10,
            max_duration: Some(std::time::Duration::ZERO),
        });
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new("timeout", Request::Step { frames: 1 }),
        );
        assert_eq!(response.observed_frame, 0);
        assert_eq!(response.state_revision, 0);
        let ResponseOutcome::Failure { error } = response.outcome else {
            panic!("expected timeout")
        };
        assert_eq!(error.code, ErrorCode::Timeout);
        assert_eq!(error.details["completed_frames"], 0);
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn wall_clock_timeout_preserves_completed_tick_and_success_revision() {
        for frames in [1, 3] {
            let (mut app, mut inspector) = inspected_app();
            let first = inspector.handle(
                &mut app,
                &RequestEnvelope::new("first", Request::Step { frames: 1 }),
            );
            assert_eq!(first.state_revision, 1);
            app.add_systems(FixedUpdate, || {
                std::thread::sleep(std::time::Duration::from_millis(40))
            });
            inspector.set_step_budget(super::StepBudget {
                max_frames: 10,
                max_duration: Some(std::time::Duration::from_millis(20)),
            });
            let response = inspector.handle(
                &mut app,
                &RequestEnvelope::new("timeout", Request::Step { frames }),
            );
            assert_eq!(response.observed_frame, 2);
            assert_eq!(response.state_revision, 1);
            assert_eq!(app.world().iter::<Position>().next().unwrap().1.0, 2);
            let ResponseOutcome::Failure { error } = response.outcome else {
                panic!("expected timeout")
            };
            assert_eq!(error.code, ErrorCode::Timeout);
            assert_eq!(error.details["requested_frames"], frames);
            assert_eq!(error.details["completed_frames"], 1);
            // A timeout is a request failure, not a stored system error.
            inspector.set_step_budget(super::StepBudget {
                max_frames: 10,
                max_duration: None,
            });
            let next = inspector.handle(
                &mut app,
                &RequestEnvelope::new("next", Request::Step { frames: 1 }),
            );
            assert_eq!(next.observed_frame, 3);
            assert_eq!(next.state_revision, 2);
            assert!(matches!(next.outcome, ResponseOutcome::Success { .. }));
        }
    }

    #[test]
    fn entity_pages_expose_names_and_opaque_component_types() {
        let (mut app, mut inspector) = inspected_app();
        let request = RequestEnvelope::new(
            "entities",
            Request::Entities {
                query: EntityQuery {
                    name: Some("player".to_owned()),
                    with_components: Vec::new(),
                },
                page: PageRequest::default(),
            },
        );

        let response = inspector.handle(&mut app, &request);
        let ResponseOutcome::Success {
            response: Response::Entities(page),
        } = response.outcome
        else {
            panic!("expected an entity page")
        };

        assert_eq!(page.entities.len(), 1);
        assert_eq!(page.entities[0].name.as_deref(), Some("player"));
        assert!(
            page.entities[0]
                .components
                .iter()
                .any(|name| name.ends_with("::Position"))
        );
    }

    #[test]
    fn mutation_requires_explicit_enablement() {
        let (mut app, mut inspector) = inspected_app();
        let request = RequestEnvelope::new(
            "set",
            Request::SetField {
                entity: EntityId {
                    index: 0,
                    generation: 0,
                },
                component: "Position".to_owned(),
                field: "x".to_owned(),
                value: 2.into(),
            },
        );

        let response = inspector.handle(&mut app, &request);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::MutationDisabled,
                    ..
                }
            }
        ));
    }
    fn metadata(name: &str) -> titan_protocol::CommandMetadata {
        titan_protocol::CommandMetadata {
            name: name.to_owned(),
            description: String::new(),
            arguments: Default::default(),
        }
    }

    #[derive(serde::Deserialize)]
    #[serde(deny_unknown_fields)]
    struct MoveArgs {
        amount: i32,
    }

    #[test]
    fn commands_are_typed_sorted_and_only_success_advances_revision() {
        let (mut app, mut inspector) = inspected_app();
        inspector
            .register_command::<MoveArgs>(metadata("move"), |app, args| {
                if args.amount < 0 {
                    return Err(titan_protocol::ProtocolError::new(
                        ErrorCode::InvalidValue,
                        "amount must be positive",
                    ));
                }
                app.world_mut().iter_mut::<Position>().next().unwrap().1.0 += args.amount;
                Ok(())
            })
            .unwrap();
        inspector
            .register_command::<MoveArgs>(metadata("alpha"), |_, _| Ok(()))
            .unwrap();
        assert!(
            inspector
                .register_command::<MoveArgs>(metadata("move"), |_, _| Ok(()))
                .is_err()
        );
        let response = inspector.handle(&mut app, &RequestEnvelope::new("list", Request::Commands));
        let ResponseOutcome::Success {
            response: Response::Commands { commands },
        } = response.outcome
        else {
            panic!("expected command list")
        };
        assert_eq!(
            commands
                .iter()
                .map(|command| command.name.as_str())
                .collect::<Vec<_>>(),
            ["alpha", "move"]
        );
        for arguments in [
            serde_json::json!({}),
            serde_json::json!({"amount": "bad"}),
            serde_json::json!({"amount": -1}),
            serde_json::json!({"amount": 2, "extra": true}),
        ] {
            let response = inspector.handle(
                &mut app,
                &RequestEnvelope::new(
                    "bad",
                    Request::Invoke {
                        name: "move".into(),
                        arguments: serde_json::from_value(arguments).unwrap(),
                    },
                ),
            );
            assert_eq!(response.state_revision, 0);
            assert!(matches!(
                response.outcome,
                ResponseOutcome::Failure {
                    error: titan_protocol::ProtocolError {
                        code: ErrorCode::InvalidValue,
                        ..
                    }
                }
            ));
            assert_eq!(app.world().iter::<Position>().next().unwrap().1.0, 0);
        }
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "valid",
                Request::Invoke {
                    name: "move".into(),
                    arguments: [("amount".into(), 5.into())].into(),
                },
            ),
        );
        assert_eq!(response.state_revision, 1);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Success {
                response: Response::Applied { applied_frame: 0 }
            }
        ));
        assert_eq!(app.world().iter::<Position>().next().unwrap().1.0, 5);
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "missing",
                Request::Invoke {
                    name: "missing".into(),
                    arguments: Default::default(),
                },
            ),
        );
        assert_eq!(response.state_revision, 1);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::NotFound,
                    ..
                }
            }
        ));
    }

    #[test]
    fn hooks_advertise_capabilities_and_capture_does_not_mutate_revision() {
        let (mut app, mut inspector) = inspected_app();
        assert_eq!(
            inspector.capabilities().operations,
            [
                titan_protocol::Operation::Inspect,
                titan_protocol::Operation::Step
            ]
        );
        let unsupported =
            inspector.handle(&mut app, &RequestEnvelope::new("capture", Request::Capture));
        assert!(matches!(
            unsupported.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::Unsupported,
                    ..
                }
            }
        ));
        inspector.register_input_handler(|app, frame, actions| {
            app.world_mut().insert_resource((frame, actions.clone()));
            Ok(())
        });
        inspector.register_capture_handler(|_| {
            Ok(titan_protocol::CaptureResult {
                identity: Default::default(),
                width: 1,
                height: 1,
                format: "ppm".into(),
                artifact: "capture.ppm".into(),
                checksum: "abc".into(),
            })
        });
        assert!(
            inspector
                .capabilities()
                .operations
                .contains(&titan_protocol::Operation::InjectInput)
        );
        assert!(
            inspector
                .capabilities()
                .operations
                .contains(&titan_protocol::Operation::Capture)
        );
        let stale = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "stale",
                Request::InjectInput {
                    frame: 0,
                    actions: Default::default(),
                },
            ),
        );
        assert_eq!(stale.state_revision, 0);
        assert!(matches!(stale.outcome, ResponseOutcome::Failure { .. }));
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "input",
                Request::InjectInput {
                    frame: 3,
                    actions: [("jump".into(), titan_protocol::InputValue::Button(true))].into(),
                },
            ),
        );
        assert_eq!(response.state_revision, 1);
        assert_eq!(response.observed_frame, 0);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Success {
                response: Response::Applied { applied_frame: 3 }
            }
        ));
        let response =
            inspector.handle(&mut app, &RequestEnvelope::new("capture", Request::Capture));
        assert_eq!(response.state_revision, 1);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Success {
                response: Response::Capture(_)
            }
        ));
    }

    #[test]
    fn deferred_command_failures_are_structured_and_do_not_advance_revision() {
        let (mut app, mut inspector) = inspected_app();
        inspector
            .register_command::<MoveArgs>(metadata("remove_twice"), |app, _| {
                let entity = app.world().entities().next().unwrap();
                let mut commands = app.world_mut().commands();
                commands.despawn(entity);
                commands.despawn(entity);
                Ok(())
            })
            .unwrap();
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "bad",
                Request::Invoke {
                    name: "remove_twice".into(),
                    arguments: [("amount".into(), 1.into())].into(),
                },
            ),
        );
        assert_eq!(response.state_revision, 0);
        let ResponseOutcome::Failure { error } = response.outcome else {
            panic!("expected failure")
        };
        assert_eq!(error.code, ErrorCode::Internal);
        assert_eq!(error.details["deferred_errors"][0]["operation"], "despawn");
        assert_eq!(app.world().entity_count(), 0);
        assert!(app.take_deferred_errors().is_empty());
    }
    #[test]
    fn failed_handlers_drain_their_deferred_writes() {
        let (mut app, mut inspector) = inspected_app();
        inspector
            .register_command::<MoveArgs>(metadata("reject"), |app, _| {
                app.world_mut().commands().spawn_with(Position(20));
                Err(titan_protocol::ProtocolError::new(
                    ErrorCode::InvalidValue,
                    "rejected after queueing",
                ))
            })
            .unwrap();
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "reject",
                Request::Invoke {
                    name: "reject".into(),
                    arguments: [("amount".into(), 1.into())].into(),
                },
            ),
        );
        assert!(matches!(response.outcome, ResponseOutcome::Failure { .. }));
        assert_eq!(response.state_revision, 0);
        assert_eq!(app.world().entity_count(), 2);
        assert!(app.apply_deferred().is_ok());
        assert_eq!(app.world().entity_count(), 2);
    }

    #[test]
    fn failed_step_reports_partial_progress_without_success_revision() {
        let (mut app, mut inspector) = inspected_app();
        app.add_systems(FixedUpdate, |world: &mut crate::World| {
            let entity = world.entities().next().unwrap();
            let mut commands = world.commands();
            commands.despawn(entity);
            commands.despawn(entity);
        });
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new("step", Request::Step { frames: 3 }),
        );
        assert_eq!(response.observed_frame, 1);
        assert_eq!(response.state_revision, 0);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::Internal,
                    ..
                }
            }
        ));
    }
    #[test]
    fn zero_page_limit_is_rejected_instead_of_repeating_cursor() {
        let (mut app, mut inspector) = inspected_app();
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "page",
                Request::Entities {
                    query: EntityQuery::default(),
                    page: PageRequest {
                        cursor: None,
                        limit: 0,
                    },
                },
            ),
        );
        assert_eq!(response.state_revision, 0);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::InvalidValue,
                    ..
                }
            }
        ));
    }

    #[test]
    fn input_hooks_flush_deferred_failures_before_reporting_success() {
        let (mut app, mut inspector) = inspected_app();
        inspector.register_input_handler(|app, _, _| {
            let entity = app.world().entities().next().unwrap();
            let mut commands = app.world_mut().commands();
            commands.despawn(entity);
            commands.despawn(entity);
            Ok(())
        });
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "input",
                Request::InjectInput {
                    frame: 1,
                    actions: Default::default(),
                },
            ),
        );
        assert_eq!(response.state_revision, 0);
        let ResponseOutcome::Failure { error } = response.outcome else {
            panic!("expected deferred failure")
        };
        assert_eq!(error.code, ErrorCode::Internal);
        assert_eq!(error.details["deferred_errors"][0]["operation"], "despawn");
        assert_eq!(app.world().entity_count(), 0);
        assert!(app.apply_deferred().is_ok());
    }

    #[test]
    fn rejected_input_hooks_drain_deferred_writes() {
        let (mut app, mut inspector) = inspected_app();
        inspector.register_input_handler(|app, _, _| {
            app.world_mut().commands().spawn_with(Position(20));
            Err(titan_protocol::ProtocolError::new(
                ErrorCode::InvalidValue,
                "rejected after queueing",
            ))
        });
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "input",
                Request::InjectInput {
                    frame: 1,
                    actions: Default::default(),
                },
            ),
        );
        assert_eq!(response.state_revision, 0);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::InvalidValue,
                    ..
                }
            }
        ));
        assert_eq!(app.world().entity_count(), 2);
        assert!(app.apply_deferred().is_ok());
        assert_eq!(app.world().entity_count(), 2);
    }

    #[test]
    fn input_hooks_do_not_run_with_outstanding_deferred_errors() {
        let (mut app, mut inspector) = inspected_app();
        let entity = app.world().entities().next().unwrap();
        let mut commands = app.world_mut().commands();
        commands.despawn(entity);
        commands.despawn(entity);
        inspector
            .register_input_handler(|_, _, _| panic!("hook ran before old failure was reported"));
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "input",
                Request::InjectInput {
                    frame: 1,
                    actions: Default::default(),
                },
            ),
        );
        assert_eq!(response.state_revision, 0);
        assert!(matches!(
            response.outcome,
            ResponseOutcome::Failure {
                error: titan_protocol::ProtocolError {
                    code: ErrorCode::Internal,
                    ..
                }
            }
        ));
    }
    #[test]
    fn missing_typed_resources_are_structured_protocol_failures() {
        struct Missing;
        let (mut app, mut inspector) = inspected_app();
        app.add_systems(FixedUpdate, |_: crate::Res<Missing>| {
            panic!("missing resource system ran")
        });
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new("missing-resource", Request::Step { frames: 3 }),
        );
        assert_eq!(response.observed_frame, 1);
        assert_eq!(response.state_revision, 0);
        let ResponseOutcome::Failure { error } = response.outcome else {
            panic!("expected system failure")
        };
        assert_eq!(error.code, ErrorCode::Internal);
        assert_eq!(
            error.details["system_errors"][0]["kind"],
            "missing_resource"
        );
        assert!(
            error.details["system_errors"][0]["type_name"]
                .as_str()
                .unwrap()
                .ends_with("::Missing")
        );
    }
}

#[cfg(test)]
mod field_tests {
    use super::*;
    use titan_protocol::ResponseOutcome;
    #[derive(crate::Component)]
    struct Position {
        x: i32,
        limit: i32,
    }
    fn metadata() -> FieldMetadata {
        FieldMetadata {
            type_name: "i32".into(),
            description: "horizontal tile".into(),
            writable: false,
            minimum: Some(0.0),
            maximum: Some(10.0),
            unit: Some("tile".into()),
        }
    }
    fn register(inspector: &mut Inspector) {
        inspector
            .register_field::<Position, i32>(
                "x",
                metadata(),
                |p| p.x,
                |p, v| {
                    if *v > p.limit {
                        Err(ProtocolError::new(
                            ErrorCode::InvalidValue,
                            "beyond entity limit",
                        ))
                    } else {
                        Ok(())
                    }
                },
                |p, v| p.x = v,
            )
            .unwrap();
        inspector
            .register_read_only_field::<Position, i32>("limit", metadata(), |p| p.limit)
            .unwrap();
    }
    fn request(entity: Entity, field: &str, value: serde_json::Value) -> RequestEnvelope {
        RequestEnvelope::new(
            "set",
            Request::SetField {
                entity: to_protocol_entity(entity),
                component: std::any::type_name::<Position>().into(),
                field: field.into(),
                value,
            },
        )
    }
    fn has_mutate(inspector: &Inspector) -> bool {
        inspector
            .capabilities()
            .operations
            .contains(&Operation::Mutate)
    }
    #[test]
    fn typed_fields_reflect_metadata_and_reject_without_mutation() {
        let mut app = App::new();
        let entity = app.world_mut().spawn();
        app.world_mut()
            .insert(entity, Position { x: 1, limit: 8 })
            .unwrap();
        let mut config = InspectionConfig::controlled("test", "project");
        config.mutation_enabled = true;
        let mut inspector = Inspector::new(config);
        assert!(!has_mutate(&inspector));
        register(&mut inspector);
        assert!(has_mutate(&inspector));
        let accepted = inspector.handle(&mut app, &request(entity, "x", 5.into()));
        assert_eq!(accepted.state_revision, 1);
        assert_eq!(accepted.observed_frame, 0);
        assert!(matches!(
            accepted.outcome,
            ResponseOutcome::Success {
                response: Response::Applied { applied_frame: 0 }
            }
        ));
        for (field, value, code) in [
            ("x", serde_json::json!("5"), ErrorCode::InvalidValue),
            ("x", (-1).into(), ErrorCode::InvalidValue),
            ("x", 11.into(), ErrorCode::InvalidValue),
            ("x", 9.into(), ErrorCode::InvalidValue),
            ("missing", 2.into(), ErrorCode::ReadOnly),
            ("limit", 2.into(), ErrorCode::ReadOnly),
        ] {
            let rejected = inspector.handle(&mut app, &request(entity, field, value));
            assert_eq!(rejected.state_revision, 1);
            assert_eq!(app.world().get::<Position>(entity).unwrap().x, 5);
            assert!(
                matches!(rejected.outcome,ResponseOutcome::Failure {error} if error.code==code)
            );
        }
        let details = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "inspect",
                Request::Entity {
                    entity: to_protocol_entity(entity),
                },
            ),
        );
        let ResponseOutcome::Success {
            response: Response::Entity(details),
        } = details.outcome
        else {
            panic!("entity")
        };
        let component = std::any::type_name::<Position>();
        assert_eq!(
            details.components[component],
            serde_json::json!({"x":5,"limit":8})
        );
        assert!(details.component_fields[component]["x"].writable);
        assert!(!details.component_fields[component]["limit"].writable);
        assert_eq!(details.component_fields[component]["x"].maximum, Some(10.0));
        app.world_mut().remove::<Position>(entity);
        let missing = inspector.handle(&mut app, &request(entity, "x", 2.into()));
        assert!(
            matches!(missing.outcome,ResponseOutcome::Failure {error} if error.code==ErrorCode::NotFound)
        );
        app.world_mut().despawn(entity);
        let recycled = app.world_mut().spawn();
        app.world_mut()
            .insert(recycled, Position { x: 3, limit: 8 })
            .unwrap();
        let stale = inspector.handle(&mut app, &request(entity, "x", 2.into()));
        assert!(
            matches!(stale.outcome,ResponseOutcome::Failure {error} if error.code==ErrorCode::NotFound)
        );
        assert_eq!(stale.state_revision, 1);
        assert_eq!(app.world().get::<Position>(recycled).unwrap().x, 3);
    }
    #[test]
    fn bounds_preserve_integer_precision_and_fractional_ordering() {
        use std::cmp::Ordering::*;
        #[derive(crate::Component)]
        struct Wide(u64);
        let mut app = App::new();
        let entity = app.world_mut().spawn();
        app.world_mut().insert(entity, Wide(1)).unwrap();
        let mut config = InspectionConfig::controlled("test", "project");
        config.mutation_enabled = true;
        let mut inspector = Inspector::new(config);
        let mut bounds = metadata();
        bounds.maximum = Some(9_007_199_254_740_992.0);
        inspector
            .register_field::<Wide, u64>(
                "value",
                bounds,
                |wide| wide.0,
                |_, _| Ok(()),
                |wide, value| wide.0 = value,
            )
            .unwrap();
        let response = inspector.handle(
            &mut app,
            &RequestEnvelope::new(
                "wide",
                Request::SetField {
                    entity: to_protocol_entity(entity),
                    component: std::any::type_name::<Wide>().into(),
                    field: "value".into(),
                    value: serde_json::json!(9_007_199_254_740_993_u64),
                },
            ),
        );
        assert!(
            matches!(response.outcome,ResponseOutcome::Failure {error} if error.code==ErrorCode::InvalidValue)
        );
        assert_eq!(response.state_revision, 0);
        assert_eq!(app.world().get::<Wide>(entity).unwrap().0, 1);
        for (value, bound, expected) in [
            (
                serde_json::json!(9_007_199_254_740_993_u64),
                9_007_199_254_740_992.0,
                Greater,
            ),
            (
                serde_json::json!(-9_007_199_254_740_993_i64),
                -9_007_199_254_740_992.0,
                Less,
            ),
            (
                serde_json::json!(u64::MAX),
                18_446_744_073_709_551_616.0,
                Less,
            ),
            (
                serde_json::json!(i64::MIN),
                -9_223_372_036_854_775_808.0,
                Equal,
            ),
            (serde_json::json!(2), 2.5, Less),
            (serde_json::json!(-2), -2.5, Greater),
        ] {
            assert_eq!(numeric_cmp(&value, bound), expected);
        }
    }

    #[test]
    fn registration_is_explicit_and_disabled_mutations_take_precedence() {
        let mut app = App::new();
        let mut inspector = Inspector::new(InspectionConfig::controlled("test", "project"));
        register(&mut inspector);
        assert!(!has_mutate(&inspector));
        assert!(
            inspector
                .register_read_only_field::<Position, i32>("x", metadata(), |p| p.x)
                .is_err()
        );
        assert!(
            inspector
                .register_read_only_field::<Position, i32>(" ", metadata(), |p| p.x)
                .is_err()
        );
        let mut invalid = metadata();
        invalid.minimum = Some(20.0);
        assert!(
            inspector
                .register_read_only_field::<Position, i32>("bad", invalid, |p| p.x)
                .is_err()
        );
        assert_eq!(
            inspector.component_field_metadata()[std::any::type_name::<Position>()].len(),
            2
        );
        let result = inspector.handle(
            &mut app,
            &request(Entity::from_parts(99, 99), "x", 2.into()),
        );
        assert!(
            matches!(result.outcome,ResponseOutcome::Failure {error} if error.code==ErrorCode::MutationDisabled)
        );
        assert_eq!(result.state_revision, 0);
    }
}
